### ISSUE TITLE
Sorry, newbie question

### ISSUE THREAD

**Issue by vishae** [zsbenke/dayone-to-wordpress#1]
I just tried running your script and got the following error message, what am I missing?

```
ruby ~/Downloads/dayone-to-wordpress-master/day_one_to_wordpress.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mime/types (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/serena/Downloads/dayone-to-wordpress-master/day_one_to_wordpress.rb:2:in `<main>'
```

**Comment by zsbenke** [comment]
@vishae forgot to mention, there is another dependecy needed. You can install it by running:

`sudo gem install mime-types`

[Updated the documentation](https://github.com/zsbenke/dayone-to-wordpress/commit/99a281e300febdaf1b7389ffae9ceabc3521f282).
